spring:
    devtools:
        restart:
            enabled: true
    datasource:
        initialize: true
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    thymeleaf:
        cache: false
    h2:
      console:
        enabled: true